### ISSUE TITLE
After entering the 'secret' and pressing "enter" on Windows, there is no new line added to the terminal

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-authenticator-cli#22]
This is a known issue in `rpassword` crate (https://github.com/conradkdotcom/rpassword/issues/32) for which @joshuef has already sent a PR to fix it: https://github.com/conradkdotcom/rpassword/pull/33

This isssue is just to track it since we are temporarily using our own forked repo until that PR gets merged in.

**Comment by conradkdotcom** [comment]
@bochaco I've just published the `rpassword` fix on crates.io with version number `3.0.1`. Thanks @joshuef !

**Comment by bochaco** [comment]
cool! thanks @conradkdotcom !
