### ISSUE TITLE
Version reported by safe_auth binary is not the correct one

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe-authenticator-cli#67]
As reported on the forum: https://safenetforum.org/t/new-release-vault-phase-1-real-vault/29712/44, when doing `safe_auth --version` on the binary downloaded from https://github.com/maidsafe/safe-authenticator-cli/releases/download/0.2.0/safe_authenticator_cli-0.2.0-x86_64-unknown-linux-gnu.tar it reports the v`0.1.0`

**Comment by Sascha-1** [comment]
Hasn't this been fixed? Should this bug be closed?

**Comment by bochaco** [comment]
Yes, thanks @Sascha-1 !
